### ISSUE TITLE
How do i get the miidata from pretendo

### ISSUE THREAD

**Issue by McWifiYt** [GabIsAwesome/accountfile-generator#1]
Is it the mii studio data param as it doesn't seem to work as when i put that into the site and add the data it doesn't show the user and doing it to the default user resets account.dat

**Comment by McWifiYt** [comment]
Okay i found it but now the user disappears when modifing the account.dat from the user select screen on cemu

**Comment by McWifiYt** [comment]
and doing it to default user still resets the account.dat for it

**Comment by stalker57241** [comment]
> Okay i found it but now the user disappears when modifing the account.dat from the user select screen on cemu
Where it is?!

**Comment by McWifiYt** [comment]
I found it when editing my mii on pretendo.network and going into my console on chrome and at the top it showed it

**Comment by GabIsAwesome** [comment]
I'm so sorry, github did not notify me at all about this.
You can get it from [PNIDLT](https://pnidlt.isledelfino.net)'s API, just click on the API button, then replace [Pretendo Network ID] with your PNID and your mii data will be there.

**Comment by McWifiYt** [comment]
It's okay. I managed to find it with the pretendo mii editor and looking in the console
